image: ${CI_BUILD_ENVIRONMENT_IMAGE}:${CI_BUILD_ENVIRONMENT_IMAGE_TAG}

stages:
  - check
  - build
  - test
  - documentation
  - deploy

include:
  - project: 'brgm/modelisation-geologique/templates'
    ref: master
    file:
      - '/gitlab-ci/check.yml'
      - '/gitlab-ci/build.yml'
      - '/gitlab-ci/test.yml'
      - '/gitlab-ci/deploy.yml'

variables:
  TARGET_PYTHON_PACKAGE_NAME: MeshTools
  TARGET_PYTEST_DIRECTORY: tests/ci

# pages:
#   stage: documentation
#   tags:
#     - docker
#   only:
#     - master
#   before_script:
#     - source activate py39
#     - python -m pip install dist/MeshTools-*.whl
#     - mkdir -p public
#   script:
#     - /bin/bash -e docs/generate_doc.bash
#   artifacts:
#     paths:
#     - public
