# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

image: docker:stable

services:
  - docker:stable-dind

variables:
  CI_REGISTRY_IMAGE: registry.gitlab.inria.fr/charms/meshtools
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
  # and https://gitlab.inria.fr/charms/ComPASS/issues/72
  DOCKER_DRIVER: overlay2
  # Introduced with docker 19.03
  # cf. https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  # FIXME: this should be replaced by correct certificates
  DOCKER_TLS_CERTDIR: ""

# this sequence will force to have unit tests in docker image. Making unit test before build docker image help remove unit test, but need to split dockerfile multijob build.
stages:
    - build_docker_environments
    - build
    - test
    - release

before_script:
  # - echo "Preparing build..."
  # - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.inria.fr
   

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

# here we build specific docker environments
# (cf. docker/README.md)
build_docker_environments:
  stage: build_docker_environments
  tags:
    - build
  only:
    - /^docker_evt_.*$/
  script:
    - docker build --force-rm --cache-from $CI_REGISTRY_IMAGE/build-environment --pull --tag $CI_REGISTRY_IMAGE/build-environment docker/build
    - docker push $CI_REGISTRY_IMAGE/build-environment
    - docker build --force-rm --cache-from $CI_REGISTRY_IMAGE/run-environment --pull --tag $CI_REGISTRY_IMAGE/run-environment docker/run
    - docker push $CI_REGISTRY_IMAGE/run-environment

build:
  stage: build
  tags:
    - build
  script:
#    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --force-rm --cache-from $CI_REGISTRY_IMAGE:latest --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
    #TODO
    #how to use docker cache ? split dockerfile to have a build image.fixed.
    #how to prevent from rebuild all code when only test change.
    # add gitlab runner docker in slave 2 to run dind
    # clean mechanism for docker images ?

integration_test:
  stage: test
  tags:
    - test
  script:
    - echo "integration test shall not be run as root"
    #- docker run --rm -v $PWD:/localfs $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG MeshTools/vtkwriters.py

#release only on master and if tests passed, maybe another tag should be the number in Git Tag for master! and add in only : Tag: to release only when master is tagged.
release:
  stage: release
  tags:
    - build
  script:
    # - docker pull $CI_REGISTRY_IMAGE:master
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
  when: on_success

tag-release:
  stage: release
  tags:
    - build
  script:
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  when: on_success
